OOMS/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'OOMS.views.home', name='home'),
    # url(r'^OOMS/', include('OOMS.foo.urls')),


    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'home.views.index', name='home'),
    (r'^about/', 'home.views.about'),
    (r'^author/', 'home.views.author'),
    (r'^free_table', 'home.views.free_table'),
    (r'get_reservation', 'home.views.get_reservation'),
    (r'^export_excel/', 'home.views.export_excel'),
    (r'suggestion/$', 'suggestion.views.suggestion'),

    (r'^staff/', include('staff.urls')),
)

staff/urls.py
# -*- coding:utf-8 -*-
__author__ = 'halfopen'

from django.conf.urls import *
from staff.views import *


urlpatterns = patterns(
    '',
    (r'^$', display_booking),
    (r'^display', display_booking),
    (r'^cancel', cancel_booking),
    (r'^add', add_booking),
    (r'^book_table', book_table),
    (r'^tables', show_tables),
    (r'^table_detail', table_detail),
)

restaurant/models.py
# -*- coding: utf-8 -*-
__author__ = 'halfopen'
from django.db import models


# 客户
class Customer(models.Model):
    name = models.CharField(verbose_name=u'姓名', max_length=200, null=False)
    tel = models.IntegerField(verbose_name=u'电话', max_length=15, null=False, unique=True)
    # email = models.EmailField(verbose_name=u'邮箱')

    class Meta:
        verbose_name = u"客户"
        verbose_name_plural = u"客户"
        ordering = ['-name']

    def __unicode__(self):
        return u"姓名:%s 手机:%s" % (self.name, self.tel)


# 订餐
class Reservation(models.Model):
    customer = models.ForeignKey(Customer, verbose_name=u"订餐用户", null=False)
    number = models.IntegerField(verbose_name=u'人数', max_length=2, null=False)
    year = models.IntegerField(verbose_name=u"年", max_length=6, default=2015)
    month = models.IntegerField(verbose_name=u"月", default=1, null=False, blank=False, max_length=6,
        choices=( (1,u"1月"), (2, u"2月"), (3, u"3月"),
        (4, u"4月"), (5, u"5月"), (6, u"6月"), (7, u"7月"), (8, u"8月"), (9, u"9月"), (10,u"10月"), (11, u"11月"), (12, u"12月")))
    day = models.IntegerField(max_length=2, default=1, null=False, blank=False, choices=((1,u"1号"), (2,u"2号"),(1, "1号")
        , (2, "2号"), (3, "3号"),(4, "4号"),(5, "5号"),(6, "6号"),(7, "7号"),(8, "8号"),(9, "9号"),(10, "10号")
        , (11, "11号"), (12, "12号"),(13, "13号"),(14, "14号"),(15 ,"15号"),(16, "16号"),(17, "17号"),(18, "18号")
        , (19, "19号"), (20, "20号"),(21, "21号"),(22, "22号"),(23, "23号"),(24, "24号"),(25, "25号"),(26, "26号")
        , (27, "27号"), (28, "28号"),(29, "29号"),(30, "30号"),(31, "31号")))
    time = models.IntegerField(verbose_name=u"时间段", default="moon", null=False, blank=False,
        choices=((9, u"早上"), (12, u"上午"), (15, u"下午"), (18, u"晚上")), max_length = 10)
    is_valid = models.BooleanField(verbose_name=u"是否有效", default=True, blank=False, null=False)
    has_table = models.BooleanField(verbose_name=u"是否已经分配桌子", default=False)

    class Meta:
        verbose_name = u"订单"
        verbose_name_plural = u"订单"
        ordering = ['-is_valid']

    def __unicode__(self):
        # date = str(self.year)+u" - "+str(self.month)+str(self.day)+str(self.time)
        date = u" "
        if self.is_valid:
            return u"%s %d人在%s的订单" % (self.customer,self.number,date)
        else:
            return u"无效订单:%s %d人在%s的订单" % (self.customer,self.number, date)

    # 检查订单是否过期(应该结账的时候手动添加)
    def check_valid(self):
        pass


# 桌子
class Table(models.Model):
    table_no = models.IntegerField(max_length=5, null=False, unique=True, verbose_name=u"桌位号")
    is_booked = models.BooleanField(verbose_name=u"是否有人预定")
    size = models.IntegerField(max_length=2, verbose_name=u"可容纳人数", default=8)
    reservation = models.ManyToManyField(Reservation, verbose_name=u"已有订单", null=True, blank=True)
    info = models.CharField(max_length=200, verbose_name=u"座位信息", null=True, blank=True, default=u"xx餐厅的xx楼xx位置座位")

    class Meta:
        verbose_name = u"桌位"
        verbose_name_plural = u"桌位"
        ordering = ['table_no']

    def __unicode__(self):
        if self.is_booked:
            return u"%03d 号桌，可容纳%d人" % (self.table_no, self.size)
        else:
            return u"%03d 号桌，可容纳%d人，空闲" % (self.table_no, self.size)

    # 重置桌子状态
    def reset(self):
        self.is_booked = False
        self.reservation.remove()
        print u"清空订单"
        self.save()

    # 预定桌子
    def book_table(self, reservation_id):
        rsv = Reservation.objects.get(pk=reservation_id)
        if rsv is None:
            return False
        self.reservation.add(rsv)
        self.is_booked = True
        self.save()
        return True

    # 去除无效订单
    def remove_invalid(self):
        invalid_rsv = Reservation.objects.filter(is_valid=False)
        for i in invalid_rsv:
            self.reservation.remove(i)
        self.save()

staff/models.py
# -*- coding: utf-8 -*-
import time
import requests
from django.db import models
from django.contrib.auth.models import User


class Staff(models.Model):
    name = models.CharField(max_length=200, null=False, unique=True, verbose_name=u"姓名")

    class Meta:
        verbose_name = u"员工"
        verbose_name_plural = u"员工"
        #ordering = ['-']

    def __unicode__(self):
        return u"%s" % self.name


class ReceptionList(models.Model):
    user = models.ForeignKey(Staff)

    class Meta:
        verbose_name = u"接待员"
        verbose_name_plural = u"接待员"
        #ordering = ['-']

    def __unicode__(self):
        return u"接待员:%s" % self.user.name

    def record_booking(self):
        pass

    def record_arrival(self):
        pass

    def cancel_booking(self):
        pass

    def change_table(self):
        pass


class HeadWaiter(models.Model):
    user = models.ForeignKey(Staff)

    class Meta:
        verbose_name = u"领班"
        verbose_name_plural = u"领班"
        #ordering = ['-']

    def __unicode__(self):
        return u"领班:%s" % self.user.name

staff/views.py
# -*- coding: utf-8 -*-
# Create your views here.

from models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from utils import render_json
from restaurant.models import *
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction

WEB_INDEX = "http://www.myooms.com:8000"


# 首页
def index(req):
    return render_to_response("staff/index.html", locals())


# 显示所有桌子
def display_booking(req):
    reservations = Reservation.objects.filter(is_valid=True).order_by('-pk').order_by("-is_valid")
    return render_to_response("staff/index.html", locals())


# 显示所有桌子
def show_tables(req):
    tables = Table.objects.filter()
    #print tables
    return render_to_response("staff/table.html", locals())


# 重置桌子状态
def reset_table(req):
    if req.GET.has_key("id"):
        t_id = req.GET["id"]
        try:
            table = Table.objects.get(pk=t_id)
            table.reset()
        except ObjectDoesNotExist:
            info = u"桌子不存在"
            return HttpResponseRedirect(WEB_INDEX)
    else:
        return HttpResponseRedirect(WEB_INDEX+"/staff")


# 显示桌子详情
def table_detail(req):
    if req.GET.has_key("id"):
        t_id = req.GET["id"]
        try:
            table = Table.objects.get(pk=t_id)
            reservations = table.reservation.filter(is_valid=True)
            print reservations
        except ObjectDoesNotExist:
            info = u"桌子不存在"
            return HttpResponseRedirect(WEB_INDEX+"/staff")
        return render_to_response("staff/table_detail.html", locals())
    else:
        return HttpResponseRedirect(WEB_INDEX+"/staff")


# 取消
def cancel_booking(req):
    dict = {}
    info = 'Data log save success'
    try:
        if req.POST.has_key('id'):
            r_id = req.POST['id']
            reservation = Reservation.objects.get(id=r_id)
        else:
            return render_json("False")
    except ObjectDoesNotExist:
        return render_json("False")

    tables = Table.objects.filter(reservation=reservation)
    for t in tables:
        t.reset()
    reservation.is_valid = False
    reservation.save()
    return render_json("True")


# 添加订单
@transaction.commit_manually
def add_booking(req):
    if req.method == "POST":
        try:
            print req.POST
            name = req.REQUEST.get("name")
            tel = req.REQUEST.get("tel")
            number = req.REQUEST.get("number")
            date = req.REQUEST.get("date")
            dic = date.split("-")
            year = dic[0]
            month = dic[1]
            day = dic[2]
            time = req.REQUEST.get("time")
            try:
                customer = Customer.objects.get(name=name, tel=tel)
                # print customer
            except ObjectDoesNotExist:
                print "create new customer\n"
                try:
                    customer = Customer(name=name, tel=tel)
                    customer.save()
                    # print customer
                except:
                    info = u"新建客户失败，是否手机号已经被占用？"
                    transaction.rollback()   # 事务回退
                    return render_to_response("staff/add.html", locals())
                info = u"新建用户"
            reservation = Reservation(customer=customer, number=number,time=time, year=year, month=month, day=day, is_valid=True)
            reservation.save()
            info = u"添加成功！"
            transaction.commit() # 事务提交
            return HttpResponseRedirect(WEB_INDEX+"/staff")
        except:
            info = u"请输入相关信息进行预订"
            # print info
            return render_to_response("staff/add.html", locals())
    else:
        # print "GET"
        info = u"请添加订单"
    return render_to_response("staff/add.html", locals())


# 分配桌子
# @transaction.commit_manually
def book_table(req):
    valid_tables = []
    invalid_tables = []
    my_tables =[]
    reservation_id = 0
    # 显示桌子
    if req.method == "GET":
        try:
            reservation_id = req.REQUEST.get("id")
            reservation = Reservation.objects.get(pk=reservation_id)
            print reservation_id
            tables = Table.objects.filter() # 得到所有桌子

            for t in tables:
                #print t.reservation.filter(is_valid=True)
                #print (t.reservation.filter(is_valid=True) is None)
                if not t.reservation.filter(is_valid=True):
                    valid_tables.append(t)
                elif t.reservation.filter(year=reservation.year, month=reservation.month, day=reservation.day, time=reservation.time).exists():
                    if t.reservation.filter(pk=reservation_id).exists():
                        my_tables.append(t)
                    else:
                        invalid_tables.append(t)
                else:
                    valid_tables.append(t)
            # print reservation_id

            return render_to_response("staff/book_table.html", locals())
        except :

            return HttpResponseRedirect('../')

    # 处理Post请求
    try:
        reservation_id = req.REQUEST.get("r_id")
        try:
            reservation = Reservation.objects.get(pk=reservation_id)
        except ObjectDoesNotExist:
            return render_json("Reservation_id error")
        tables_str = req.REQUEST.get("tables_id")
        tables = []
        i = 0
        for t in tables_str.split("-"):
            i += 1
            if i == 1:
                continue
            tables.append(t)

        # 清除之前桌子
        former_tables = Table.objects.filter(reservation=reservation)
        for t in former_tables:
            t.reservation.remove(reservation)

        # 遍历桌子
        for i in tables:
            try:
                t = Table.objects.get(pk=i)
                if not t.book_table(reservation_id): # 如果预定失败
                    return render_json(u"预约桌子"+str(t.table_no)+u"失败")
                else:
                    try:
                        t.reservation.add(reservation)
                    except:
                        print u"添加预约失败"
                        return render_json(u"添加预约失败")
                    t.save()
            except ObjectDoesNotExist:
                pass
        reservation.has_table = True
        reservation.save()
    except:
        render_json("False")
    return render_json("True")

templates/staff/add.html
{%  extends "base.html" %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{{ "/static/css/staff.css" }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ "/static/js/staff.js" }}"></script>
{% endblock %}

{% block main %}
<div class="container">
    <h1 class="animated bounceInLeft">添加预约</h1><br />
<br/>
<form class="form-horizontal vertical-center" role="form" action="add_booking" method="post">
   <div class="form-group">
      <label for="firstname" class="col-sm-2 control-label">名字</label>
      <div class="col-sm-10">
         <input type="text" class="form-control" id="firstname" name="name"
            placeholder="请输入名字">
      </div>
   </div>
   <div class="form-group">
      <label for="lastname" class="col-sm-2 control-label">联系方式</label>
      <div class="col-sm-10">
         <input type="tel" class="form-control" id="lastname" name="tel"
            placeholder="联系方式">
      </div>
   </div>
   <div class="form-group">
      <label for="lastname" class="col-sm-2 control-label">人数</label>
      <div class="col-sm-10">
         <input type="text" class="form-control" id="lastname" name="number"
            placeholder="人数">
      </div>
   </div>
   <div class="form-group">
      <label for="lastname" class="col-sm-2 control-label">日期</label>
      <div class="col-sm-10">
         <input type="date" class="form-control" id="lastname" name="date"
            placeholder="时间">
      </div>
   </div>
    <div class="form-group">
      <label for="lastname" class="col-sm-2 control-label">时间</label>
      <div class="col-sm-10">
            <select id="id_time" class="form-control" name="time">
            <option value="9">早上</option>
            <option value="12">中午</option>
            <option value="15">下午</option>
            <option value="18">晚上</option>
            </select>

      </div>
   </div>
   <div class="form-group text-center">
      <div class="col-sm-offset-2 col-sm-10">
         <button type="submit" class="btn btn-green">添加订单</button>
      </div>
   </div>
</form>
</div>

<div class="clear"></div>
{% endblock %}

templates/staff/book_table.html
{%  extends "base.html" %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{{ "/static/css/staff.css" }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ "/static/js/staff.js" }}"></script>
{% endblock %}

{% block main %}
<div class="container">
    <h1 class="animated bounceInLeft">订单相关桌子分配</h1>
    <div class="row">
    <div class="col-md-12 text-center meal-list reservation singel_book" style="background: #d9edf7" r_id="{{ reservation.pk }}">
        <span class="spin"><img src="../static/img/spin/1.png"></span>
        <div class="text-bold text-center singel-line">客户名:{{ reservation.customer.name }}</div>
        <div class="blanka">&nbsp;</div>
        <div class="text-left singel-line">联系方式:{{ reservation.customer.tel }}</div>
        <div class="text-left singel-line reservation_number" number="{{ reservation.number }}">人数:{{ reservation.number }} 已选人数: <span id="total_size">0</span></div>
        <div class="text-left singel-line">日期:{{ reservation.year }}/{{ reservation.month }}/{{ reservation.day }}-{{ reservation.time }}:00</div>
        {% if my_tables %}
            <div class="text-left btn book_table" style="margin-bottom: 1%">重新分配</div>
        {% else %}
            <div class="btn book_table" style="margin-bottom: 1%">分配桌子</div>
        {% endif %}
        <br/>
      </div>
    </div>

{#        <div class="h2 text-bold">已选桌子</div>#}
{#        <div class="row">#}
{#            {% for t in my_tables %}#}
{#                <a href="table_detail?id={{ t.pk }}" class="row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list table-list table-list-selected"#}
{#                      pk="{{ t.pk }}" size="{{ t.size }}">#}
{#                <div style="text-decoration: none; color: #ffffff">#}
{#                    <div class="text-bold text-left">桌子编号:{{ t.table_no }}</div>#}
{#                    <div class="text-left">桌子大小:{{ t.size }}</div>#}
{#                    <div class="singel-line">{{ t.info }}</div>#}
{#                </div>#}
{#                </a>#}
{#            {% endfor %}#}
{#        </div>#}

        <div class="h2 text-bold">可用桌子</div>
        <div class="row">
            {% for t in my_tables %}
                <div class="animated pulse row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list table-list table-list-selected"
                      pk="{{ t.pk }}" size="{{ t.size }}">
                <div style="text-decoration: none; color: #ffffff">
                    <div class="text-bold text-left">我的桌子编号:{{ t.table_no }}</div>
                    <div class="text-left">桌子大小:{{ t.size }}</div>
                    <div class="singel-line">{{ t.info }}</div>
                </div>
                </div>
            {% endfor %}
            {% for t in valid_tables %}
                <div  class="animated pulse row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list table-list" style="cursor: pointer"
                      pk="{{ t.pk }}" size="{{ t.size }}">
                <div style="text-decoration: none; color: #ffffff">
                    <div class="text-bold text-left">桌子编号:{{ t.table_no }}</div>
                    <div class="text-left">桌子大小:{{ t.size }}</div>
                    <div class="singel-line">{{ t.info }}</div>
                </div>
                </div>
            {% endfor %}
        </div>



    <div class="h2 text-bold">不可用桌子</div>
    <div class="row">
        {% for t in invalid_tables %}
            <a href="table_detail?id={{ t.pk }}" class="animated pulse col-md-2 text-center meal-list table-list table-list-invalid">
            <div style="text-decoration: none; color: #ffffff">
                <div class="text-bold text-left">桌子编号:{{ t.table_no }}</div>
                <div class="text-left">桌子大小:{{ t.size }}</div>
                <div class="singel-line">{{ t.info }}</div>
            </div>
            </a>
        {% endfor %}
    </div>

</div>

{% endblock %}

templates/staff/index.html
{%  extends "base.html" %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{{ "/static/css/staff.css" }}" />
{% endblock %}
{% block js %}
<script type="text/javascript" src="{{ "/static/js/staff.js" }}"></script>
{% endblock %}

{% block main %}
<div class="container">


<div class="h1 class="animated bounceInLeft"">所有订单</div>
<a href="add" class="btn btn-green">添加新订单</a><br />

<div class="row">
{% for r in reservations %}
    {% if r.is_valid %}
      <div class="animated pulse row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list">
        <div class="remove-meal btn btn-danger btn-xs " pk="{{ r.pk }}" >移除</div>
        <span class="spin"><img src="../static/img/spin/1.png"></span>
        <div class="text-bold text-center singel-line text-success">客户名:{{ r.customer.name }}</div>
        <div class="">&nbsp;</div>
        <div class="singel-line text-left text-info">订单号:{{ r.pk }}&nbsp</div>
        <div class="text-left singel-line">联系方式:{{ r.customer.tel }}</div>
        <div class="text-left singel-line">人数:{{ r.number }}</div>
        <div class="text-left singel-line">日期:{{ r.year }}/{{ r.month }}/{{ r.day }}-{{ r.time }}:00</div>
        <div class="row">
            {% if not r.has_table %}
            <a href="book_table?id={{ r.pk }}" class=" col-md-12 btn btn-sm btn-orange" style="cursor: pointer; padding-right: 1%;" >分配座位</a>
            {% else %}
            <a href="book_table?id={{ r.pk }}" class=" col-md-12 btn btn-sm btn-green" style="cursor: pointer; padding-right: 1%;" >查看详情</a>
            {% endif %}
        </div>
      </div>
    {% else %}
        <div class="animated pulse row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list invalid-meal-list">
        <div class="remove-meal btn btn-danger btn-xs " pk="{{ r.pk }}" >移除</div>
        <span class="spin"><img src="../static/img/spin/1.png"></span>
        <div class="text-bold text-center singel-line text-success">客户名:{{ r.customer.name }}</div>
        <div class="">&nbsp;</div>
        <div class="singel-line text-left text-info">订单号:{{ r.pk }}&nbsp</div>
        <div class="text-left singel-line">联系方式:{{ r.customer.tel }}</div>
        <div class="text-left singel-line">人数:{{ r.number }}</div>
        <div class="text-left singel-line">日期:{{ r.year }}/{{ r.month }}/{{ r.day }}-{{ r.time }}:00</div>
        <div class="row">
            <a href="book_table?id={{ r.pk }}" class=" col-md-12 btn btn-sm btn-comment" style="cursor: pointer; padding-right: 1%;" >过期订单</a>
        </div>
      </div>
    {% endif %}
{% endfor %}
</div>

</div>

<div class="clear"></div>
{% endblock %}

templates/staff/table.html
{%  extends "base.html" %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{{ "/static/css/staff.css" }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ "/static/js/staff.js" }}"></script>
{% endblock %}

{% block main %}

<div class="container">
    <h1 class="animated bounceInLeft">所有桌子列表</h1>
    <div class="row">
        {% for t in tables %}
            <div class="animated plus row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list table-list">
                <a href="table_detail?id={{ t.pk }}" >
                <div style="text-decoration: none; color: #ffffff">
                    <div class="text-bold text-left">桌子编号:{{ t.table_no }}</div>
                    <div class="text-left">&nbsp;</div>
                    <div class="text-bold text-left">可容纳:{{ t.size }}人</div>
                    <div class="singel-line">{{ t.info }}</div>
                </div>
                </a>
            </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

templates/staff/table_detail.html
{%  extends "base.html" %}
{% block link %}
<link rel="stylesheet" type="text/css" href="{{ "/static/css/staff.css" }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ "/static/js/staff.js" }}"></script>
{% endblock %}

{% block main %}

<div class="container">
    <h1 class="animated bounceInLeft">桌子详情</h1>
    <div class="row text-center">
            <div class="col-md-6 text-center meal-list table-list">
                <a href="table_detail?id={{ table.pk }}" >
                <div style="text-decoration: none; color: #ffffff">
                    <div class="text-bold text-left">桌子编号:{{ table.table_no }}</div>
                    <div class="text-left">&nbsp;</div>
                    <div class="text-bold text-left">可容纳:{{ table.size }}人</div>
                    <div class="singel-line">{{ table.info }}</div>
                </div>
                </a>
            </div>
    </div>
    <br/>

    <h2  class="animated bounceInLeft">该桌已有订单</h2>
    <div class="row">
    {% for r in reservations %}
          <div class="row-content col-lg-2 col-sm-4 col-xs-12 text-center meal-list">
            <div class="remove-meal btn btn-danger btn-xs " pk="{{ r.pk }}" >移除</div>
            <span class="spin"><img src="../static/img/spin/1.png"></span>
            <div class="text-bold text-center singel-line text-success">客户名:{{ r.customer.name }}</div>
            <div class="">&nbsp;</div>
            <div class="singel-line text-left text-info">订单号:{{ r.pk }}&nbsp</div>
            <div class="text-left singel-line">联系方式:{{ r.customer.tel }}</div>
            <div class="text-left singel-line">人数:{{ r.number }}</div>
            <div class="text-left singel-line">日期:{{ r.year }}/{{ r.month }}/{{ r.day }}-{{ r.time }}:00</div>
            <div class="row">
                {% if not r.has_table %}
                <a href="book_table?id={{ r.pk }}" class=" col-md-12 btn btn-sm btn-orange" style="cursor: pointer; padding-right: 1%;" >分配座位</a>
                {% else %}
                <a href="book_table?id={{ r.pk }}" class=" col-md-12 btn btn-sm btn-green" style="cursor: pointer; padding-right: 1%;" >查看详情</a>
                {% endif %}
            </div>
          </div>
    {% endfor %}
</div>

{% endblock %}